scraper:
  build: .
  command: python scrapymanager.py
  ports:
    - "6023:6023"
  volumes:
    - "./olx:/olx"
  links:
    - db
    
webapi:
   build: ./webapi/
   command: npm start
   ports: 
    - "8080:8080"
   links:
    - db

db:
  image: mongo:latest
  ports:
    - "27017:27017"
