CSRF_ENABLED = True
SECRET_KEY = 'blabla'

DOCUMENTDB_HOST = 'https://mongo-olx.documents.azure.com:443/'
DOCUMENTDB_KEY = 'hJJaII1eaMs2wUHNqvjDkzRF3wOz24x8x/J7+Zfw2D91KM/LTjNXcVg8WgMV2JiaNGuTnsnInSmO8jrqDRGw/g=='

DOCUMENTDB_DATABASE = 'olxDB'
DOCUMENTDB_COLLECTION = 'rentals'
DOCUMENTDB_DOCUMENT = 'rent-doc'